### ISSUE TITLE
Document how to create a generator

### ISSUE THREAD

**Issue by matthewp** [donejs/cli#1]

**Comment by matthewp** [comment]
For now it's on the wiki here: https://github.com/donejs/cli/wiki/Writing-a-donejs-plugin

Needs to be updated, i'm not sure how to accept an argument.

**Comment by matthewp** [comment]
It's all updated, haven't verified that it works yet.

**Comment by daffl** [comment]
This is available now in https://donejs.com/generator.html (final tweaks incoming).
