### ISSUE TITLE
Allow accepting the default options for donejs init

### ISSUE THREAD

**Issue by matthewp** [donejs/cli#13]
It would be nice if we had something like `donejs init --accept-defaults` that skipped the prompt. This is primarily needed for test automation as answer prompts is hard.

**Comment by daffl** [comment]
Generators can also be automatically invoked like this: https://github.com/donejs/generator-donejs/blob/master/test/app.test.js.

**Comment by matthewp** [comment]
I'm invoking donejs init though.  This is not needed, I figured out how to answer the prompts.
