### ISSUE TITLE
Startup is slow

### ISSUE THREAD

**Issue by matthewp** [donejs/cli#3]
If I do:

```
time node_modules/.bin/donejs --version
```

I get ~1.75 seconds.  Other Node tools I get < 0.15 seconds.

I can get it down to ~0.5 seconds if I comment out [these lines](https://github.com/donejs/cli/blob/91ae47c82c447360bb9cc9122949fa53696aec49/bin/donejs#L67-L70). Can we get rid of that?  We could put it behind a different generator help flag rather than incurring the cost on every run.

**Comment by daffl** [comment]
This should be fixed with https://github.com/donejs/cli/pull/6

**Comment by matthewp** [comment]
Looks really fast now.

```
time donejs --version
0.5.2
donejs --version  0.09s user 0.02s system 98% cpu 0.114 total
```
