### ISSUE TITLE
On Windows run the .bin commands calling the .cmd file

### ISSUE THREAD

**Issue by matthewp** [donejs/cli#32]
Calling node_modules\.bin\deploy for example doesn't work on Windows, need to call node_modules\.bin\deploy.cmd

**Comment by daffl** [comment]
Didn't we change this for the CLI to `node node_modules/.bin/donejs`?

**Comment by matthewp** [comment]
No, we changed it to `node node_modules/donejs-cli/bin/donejs`.  We had to do that because on Windows calling `.bin/donejs` locks up that file and prevents it from being overwritten when the donejs init npm install happens. 

This is for a different scenario, your project is already set up and you just want to call the commands in your node_modules/.bin
