### ISSUE TITLE
Add flag for selecting all of the default options

### ISSUE THREAD

**Issue by phillipskevin** [donejs/cli#71]
It would be nice if you could do something like

```
donejs add app my-app --yes
```

and have all of the default options selected without having to hit enter for every question.

**Comment by matthewp** [comment]
Shouldn't this be a generator-donejs issue? You couldn't support this universally, I don't think, like `donejs add firebase --yes` wouldn't work. Hopefully the cli flags are passed to the generator some how, and they can interpret them as they wish.

**Comment by phillipskevin** [comment]
Actually, this is a donejs/donejs issue first, and then a generator-donejs issue. We need to add a command line flag here: https://github.com/donejs/donejs/blob/master/lib/cli/index.js#L15 or commander will exit with `error: unknown option '--yes'`.

**Comment by phillipskevin** [comment]
Issue moved to [donejs/donejs #819](https://github.com/donejs/donejs/issues/819) via [**ZenHub**](https://www.zenhub.com/)
