### ISSUE TITLE
Proposal: remove from major app/templates/documentjs.json

### ISSUE THREAD

**Issue by frank-dspeed** [donejs/cli#79]
I think documentjs.json should be move to its own generator as documentjs is no longer even a dependency.
app/templates/documentjs.json

**Comment by chasenlehara** [comment]
Was this supposed to be filed for https://github.com/donejs/generator-donejs? That file is already gone in the `major` branch: https://github.com/donejs/generator-donejs/tree/major/app/templates

**Comment by frank-dspeed** [comment]
@chasenlehara oh sorry i was probally in the wrong branch it was my fault your right
